name: pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force
